name: Environment setup

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "The python version desired."
        required: true
        default: '3.7'
        type: string

      pytorch-version:
        description: "The pytorch version desired."
        required: true
        default: '1.10.2'
        type: string

runs:
  using: "composite"
  steps:
    - name: Setup environment (conda)
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}

    - if: ${{ contains(fromJson('["lts", "nightly"]'), inputs.pytorch-version ) }}
      name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install curl -c conda-forge
        conda install pytorch cpuonly -c pytorch-${{ inputs.pytorch-version }}
        pip install .[dev,x]


    - if: ${{ contains(fromJson('["lts", "nightly"]'), inputs.pytorch-version ) == false}}
      name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install curl -c conda-forge
        conda install pytorch=${{ inputs.pytorch-version }} cpuonly -c pytorch
        pip install .[dev,x]

    - name: Environment
      shell: bash -l {0}
      run: |
        curl -O https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
        python collect_env.py
