name: Environment setup

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "The python version desired."
        required: true
        default: "3.11"
        type: string

      pytorch-version:
        description: "The pytorch version desired."
        required: true
        default: "2.1.1"
        type: string

runs:
  using: "composite"
  steps:
    - name: Setup environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - if: ${{ contains(fromJson('["nightly"]'), inputs.pytorch-version ) }}
      name: Install PyTorch nightly
      shell: bash
      run: pip install numpy --pre torch[dynamo] --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cpu/

    - if: ${{ contains(fromJson('["nightly"]'), inputs.pytorch-version ) == false}}
      name: Install pytorch
      shell: bash
      run: pip install torch==${{ inputs.pytorch-version }} --index-url https://download.pytorch.org/whl/cpu

    - name: Install Kornia dev
      shell: bash
      run: pip install .[dev,x]

    - name: Check dependencies and kornia version
      shell: bash
      run: |
        python -c "import torch;print('Pytorch version: ', torch.__version__)"
        python -c "import kornia;print('Kornia version: ', kornia.__version__)"
