from kornia.color.colormap import AUTUMN, ApplyColorMap, ColorMap, RGBColor, apply_colormap
from kornia.color.gray import (
    BgrToGrayscale,
    GrayscaleToRgb,
    RgbToGrayscale,
    bgr_to_grayscale,
    grayscale_to_rgb,
    rgb_to_grayscale,
)
from kornia.color.hls import HlsToRgb, RgbToHls, hls_to_rgb, rgb_to_hls
from kornia.color.hsv import HsvToRgb, RgbToHsv, hsv_to_rgb, rgb_to_hsv
from kornia.color.lab import LabToRgb, RgbToLab, lab_to_rgb, rgb_to_lab
from kornia.color.luv import LuvToRgb, RgbToLuv, luv_to_rgb, rgb_to_luv
from kornia.color.raw import (
    CFA,
    RawToRgb,
    RawToRgb2x2Downscaled,
    RgbToRaw,
    raw_to_rgb,
    raw_to_rgb_2x2_downscaled,
    rgb_to_raw,
)
from kornia.color.rgb import (
    BgrToRgb,
    BgrToRgba,
    LinearRgbToRgb,
    RgbaToBgr,
    RgbaToRgb,
    RgbToBgr,
    RgbToLinearRgb,
    RgbToRgba,
    bgr_to_rgb,
    bgr_to_rgba,
    linear_rgb_to_rgb,
    rgb_to_bgr,
    rgb_to_linear_rgb,
    rgb_to_rgba,
    rgba_to_bgr,
    rgba_to_rgb,
)
from kornia.color.sepia import Sepia, sepia_from_rgb
from kornia.color.xyz import RgbToXyz, XyzToRgb, rgb_to_xyz, xyz_to_rgb
from kornia.color.ycbcr import RgbToYcbcr, YcbcrToRgb, rgb_to_y, rgb_to_ycbcr, ycbcr_to_rgb
from kornia.color.yuv import (
    RgbToYuv,
    RgbToYuv420,
    RgbToYuv422,
    Yuv420ToRgb,
    Yuv422ToRgb,
    YuvToRgb,
    rgb_to_yuv,
    rgb_to_yuv420,
    rgb_to_yuv422,
    yuv420_to_rgb,
    yuv422_to_rgb,
    yuv_to_rgb,
)

__all__ = [
    "grayscale_to_rgb",
    "rgb_to_grayscale",
    "bgr_to_grayscale",
    "bgr_to_rgb",
    "rgb_to_bgr",
    "rgb_to_rgba",
    "rgb_to_hsv",
    "hsv_to_rgb",
    "rgb_to_hls",
    "hls_to_rgb",
    "rgb_to_ycbcr",
    "ycbcr_to_rgb",
    "rgb_to_y",
    "rgb_to_yuv",
    "rgb_to_yuv420",
    "rgb_to_yuv422",
    "yuv_to_rgb",
    "yuv420_to_rgb",
    "yuv422_to_rgb",
    "rgb_to_xyz",
    "xyz_to_rgb",
    "rgb_to_lab",
    "lab_to_rgb",
    "RgbToGrayscale",
    "BgrToGrayscale",
    "BgrToRgb",
    "RgbToBgr",
    "RgbToRgba",
    "RgbToHsv",
    "HsvToRgb",
    "RgbToHls",
    "HlsToRgb",
    "RgbToYcbcr",
    "YcbcrToRgb",
    "RgbToYuv",
    "RgbToYuv420",
    "RgbToYuv422",
    "YuvToRgb",
    "Yuv420ToRgb",
    "Yuv422ToRgb",
    "RgbToXyz",
    "XyzToRgb",
    "RgbToLuv",
    "LuvToRgb",
    "LabToRgb",
    "RgbToLab",
    "RgbToRaw",
    "RawToRgb",
    "RawToRgb2x2Downscaled",
    "raw_to_rgb",
    "rgb_to_raw",
    "raw_to_rgb_2x2_downscaled",
    "CFA",
    "GrayscaleToRgb",
    "luv_to_rgb",
    "rgb_to_luv",
    "bgr_to_rgba",
    "BgrToRgba",
    "linear_rgb_to_rgb",
    "LinearRgbToRgb",
    "rgb_to_linear_rgb",
    "rgba_to_rgb",
    "rgba_to_bgr",
    "RgbaToRgb",
    "RgbaToBgr",
    "RgbToLinearRgb",
    "Sepia",
    "sepia",
    "AUTUMN",
    "ApplyColorMap",
    "ColorMap",
    "RGBColor",
    "apply_colormap",
]

sepia = sepia_from_rgb
