# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright 2018 Kornia Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import pytest
import torch

import kornia
import kornia.augmentation as K

from testing.augmentation.utils import reproducibility_test
from testing.base import BaseTester


class TestSequential:
    @pytest.mark.parametrize("random_apply_weights", [None, [0.8, 0.9]])
    def test_exception(self, random_apply_weights, device, dtype):
        inp = torch.randn(1, 3, 30, 30, device=device, dtype=dtype)
        with pytest.raises(Exception):  # AssertError and NotImplementedError
            K.ImageSequential(
                K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0), random_apply_weights=random_apply_weights
            ).inverse(inp)

    @pytest.mark.parametrize("same_on_batch", [True, False, None])
    @pytest.mark.parametrize("keepdim", [True, False, None])
    @pytest.mark.parametrize("random_apply", [1, (2, 2), (1, 2), (2,), 20, True, False])
    def test_construction(self, same_on_batch, keepdim, random_apply):
        aug = K.ImageSequential(
            K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
            K.RandomAffine(360, p=1.0),
            K.RandomMixUpV2(p=1.0),
            same_on_batch=same_on_batch,
            keepdim=keepdim,
            random_apply=random_apply,
        )
        aug.same_on_batch = True
        aug.keepdim = True
        for m in aug.children():
            assert m.same_on_batch is True, m.same_on_batch
            assert m.keepdim is True, m.keepdim

    @pytest.mark.parametrize("random_apply", [1, (2, 2), (1, 2), (2,), 10, True, False])
    def test_forward(self, random_apply, device, dtype):
        inp = torch.randn(1, 3, 30, 30, device=device, dtype=dtype)
        aug = K.ImageSequential(
            K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
            kornia.filters.MedianBlur((3, 3)),
            K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
            K.ImageSequential(K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0)),
            K.ImageSequential(K.RandomAffine(360, p=1.0)),
            K.RandomAffine(360, p=1.0),
            K.RandomMixUpV2(p=1.0),
            random_apply=random_apply,
        )
        out = aug(inp)
        assert out.shape == inp.shape
        aug.inverse(inp)
        reproducibility_test(inp, aug)


@pytest.mark.usefixtures("restore_torch_rng")
class TestConventionImageSequential(BaseTester):
    """Batch-6 convention pins for `ImageSequential`.

    Literals generated by the body of each pin, executed on this worktree on 2026-09-11 with
    `.venv/bin/python` (torch 2.14.0, python 3.11, cpu, float32).
    """

    def test_wart_if_unsupported_ops_is_neither_honoured_nor_validated_4423(self, device, dtype):
        # Wart pin (#4423): `ImageSequential.if_unsupported_ops` ("raise" by default) never fires. A plain
        # `nn.Module` in the chain is silently skipped on the inverse path under every value of the flag -
        # including an invalid one, which is accepted without validation - so `inverse` undoes only the
        # invertible ops and returns something that is not the input, with no warning.
        # The deterministic checkerboard ensures the omitted blur visibly changes the output: for every
        # if_unsupported_ops value in ("raise", "skip", "bogus"), inverse equals hflip(output) exactly
        # (only the flip was undone) and differs from the input.
        # The fix lands in the repair window; do not "correct" this pin here.
        x = torch.arange(6 * 8, device=device, dtype=dtype).reshape(1, 1, 6, 8).remainder(2).expand(2, 3, -1, -1)
        assert K.ImageSequential(K.RandomHorizontalFlip(p=1.0)).if_unsupported_ops == "raise"
        for mode in ("raise", "skip", "bogus"):
            seq = K.ImageSequential(
                K.RandomHorizontalFlip(p=1.0),
                kornia.filters.GaussianBlur2d((3, 3), (1.5, 1.5)),
                if_unsupported_ops=mode,
            )
            out = seq(x)
            inverted = seq.inverse(out)
            self.assert_close(inverted, out.flip(-1))  # only the flip was undone, the blur was skipped
            assert (inverted - x).abs().max().item() > 0.1  # and the round trip is not the input

    @pytest.mark.xfail(strict=True, reason="Tracked in #4423")
    def test_convention_if_unsupported_ops_raise_raises_not_implemented(self, device, dtype):
        # Strict xfail (#4423): the intended reading is the argument's own contract - `if_unsupported_ops`
        # defaults to "raise", so inverting a chain that holds a non-invertible plain `nn.Module` must raise
        # `NotImplementedError` rather than silently skip it. This turns XPASS when the repair lands, which
        # is the signal to delete the wart pin above. Executed 2026-09-11 (torch 2.14.0, cpu): inverse returns
        # quietly.
        x = torch.rand(2, 3, 6, 8, device=device, dtype=dtype)
        seq = K.ImageSequential(
            K.RandomHorizontalFlip(p=1.0),
            kornia.filters.GaussianBlur2d((3, 3), (1.5, 1.5)),
            if_unsupported_ops="raise",
        )
        out = seq(x)
        with pytest.raises(NotImplementedError):
            seq.inverse(out)

    @pytest.mark.xfail(strict=True, reason="Tracked in #4423")
    def test_convention_if_unsupported_ops_rejects_invalid_value(self):
        # Strict xfail (#4423): construction accepts only "raise" and "skip". Executed 2026-09-11 (torch
        # 2.14.0, cpu): "bogus" is accepted without validation.
        with pytest.raises(ValueError, match="if_unsupported_ops"):
            K.ImageSequential(K.RandomHorizontalFlip(p=1.0), if_unsupported_ops="bogus")
