# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright 2018 Kornia Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import pytest
import torch

import kornia
import kornia.augmentation as K

from testing.base import BaseTester


class TestDispatcher:
    def test_many_to_many(self, device, dtype):
        input_1 = torch.randn(2, 3, 5, 6, device=device, dtype=dtype)
        input_2 = torch.randn(2, 3, 5, 6, device=device, dtype=dtype)
        mask_1 = torch.ones(2, 1, 5, 6, device=device, dtype=dtype)
        mask_2 = torch.ones(2, 1, 5, 6, device=device, dtype=dtype)
        aug_list = K.ManyToManyAugmentationDispather(
            K.AugmentationSequential(
                kornia.augmentation.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                kornia.augmentation.RandomAffine(360, p=1.0),
                data_keys=["input", "mask"],
            ),
            K.AugmentationSequential(
                kornia.augmentation.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                kornia.augmentation.RandomAffine(360, p=1.0),
                data_keys=["input", "mask"],
            ),
        )
        output = aug_list((input_1, mask_1), (input_2, mask_2))

        assert output[0][0].shape == input_1.shape
        assert output[1][0].shape == input_2.shape
        assert output[0][1].shape == mask_1.shape
        assert output[1][1].shape == mask_2.shape

    @pytest.mark.parametrize("strict", [True, False])
    def test_many_to_one(self, strict, device, dtype):
        input = torch.randn(2, 3, 5, 6, device=device, dtype=dtype)
        mask = torch.ones(2, 1, 5, 6, device=device, dtype=dtype)
        aug_list = K.ManyToOneAugmentationDispather(
            K.AugmentationSequential(
                kornia.augmentation.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                kornia.augmentation.RandomAffine(360, p=1.0),
                data_keys=["input", "mask"],
            ),
            K.AugmentationSequential(
                kornia.augmentation.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                kornia.augmentation.RandomAffine(360, p=1.0),
                data_keys=["input", "mask"],
            ),
            strict=strict,
        )
        output = aug_list(input, mask)

        assert output[0][0].shape == input.shape
        assert output[1][0].shape == input.shape
        assert output[0][1].shape == mask.shape
        assert output[1][1].shape == mask.shape

    @pytest.mark.parametrize("strict", [True, False])
    def test_many_to_one_strict_mode(self, strict):
        def _init_many_to_one(strict):
            K.ManyToOneAugmentationDispather(
                K.AugmentationSequential(
                    kornia.augmentation.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                    kornia.augmentation.RandomAffine(360, p=1.0),
                    data_keys=["input"],
                ),
                K.AugmentationSequential(
                    kornia.augmentation.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                    kornia.augmentation.RandomAffine(360, p=1.0),
                    data_keys=["input", "mask"],
                ),
                strict=strict,
            )

        if strict:
            with pytest.raises(RuntimeError):
                _init_many_to_one(strict)  # fails
        else:
            _init_many_to_one(strict)  # passes


@pytest.mark.usefixtures("restore_torch_rng")
class TestConventionDispatcher(BaseTester):
    """Batch-6 convention pins for the two dispatchers.

    Literals generated by the body of each pin, executed on this worktree on 2026-09-11 with
    `.venv/bin/python` (torch 2.14.0, python 3.11, cpu, float32); the augmentations are `p=1.0` flips, so
    nothing depends on a seed.
    """

    @staticmethod
    def _one_key_sequential():
        return K.AugmentationSequential(K.RandomHorizontalFlip(p=1.0), data_keys=["input"])

    def test_wart_many_to_many_zips_and_silently_drops_the_surplus_4422(self, device, dtype):
        # Wart pin (#4422): `ManyToManyAugmentationDispather` is documented as "as many inputs as there are
        # augmentations", but it is a bare `zip` over the two sequences and nothing checks their lengths, so
        # the longer side is silently truncated - surplus augmentations or surplus inputs just disappear, and
        # the only signal is the length of the returned list. `ManyToOneAugmentationDispather` broadcasts one
        # payload to every augmentation instead and cannot exhibit this.
        # Snippet used to generate expected: this body, executed 2026-09-11 (torch 2.14.0, cpu):
        # 3 augmentations + 1 payload -> 1 output, 3 + 2 -> 2, 2 augmentations + 3 payloads -> 2,
        # ManyToOne with 3 augmentations + 1 payload -> 3, and zero augmentations -> 0 with no error.
        # The fix lands in the repair window; do not "correct" this pin here.
        x = torch.rand(2, 3, 6, 8, device=device, dtype=dtype)
        three = K.ManyToManyAugmentationDispather(
            self._one_key_sequential(), self._one_key_sequential(), self._one_key_sequential()
        )
        assert len(three((x,))) == 1  # two augmentations silently dropped
        assert len(three((x,), (x,))) == 2  # one augmentation silently dropped
        two = K.ManyToManyAugmentationDispather(self._one_key_sequential(), self._one_key_sequential())
        assert len(two((x,), (x,), (x,))) == 2  # one input silently dropped
        assert len(K.ManyToManyAugmentationDispather()((x,))) == 0  # no augmentation at all, still no error
        broadcast = K.ManyToOneAugmentationDispather(
            self._one_key_sequential(), self._one_key_sequential(), self._one_key_sequential()
        )
        assert len(broadcast(x)) == 3
