# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright 2018 Kornia Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import pytest
import torch

import kornia
import kornia.augmentation as K
from kornia.core._compat import torch_version_lt

from testing.augmentation.utils import reproducibility_test
from testing.base import BaseTester


class TestSequential:
    @pytest.mark.parametrize("random_apply_weights", [None, [0.8, 0.9]])
    def test_exception(self, random_apply_weights, device, dtype):
        inp = torch.randn(1, 3, 30, 30, device=device, dtype=dtype)
        with pytest.raises(Exception):  # AssertError and NotImplementedError
            K.ImageSequential(
                K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0), random_apply_weights=random_apply_weights
            ).inverse(inp)

    @pytest.mark.parametrize("same_on_batch", [True, False, None])
    @pytest.mark.parametrize("keepdim", [True, False, None])
    @pytest.mark.parametrize("random_apply", [1, (2, 2), (1, 2), (2,), 20, True, False])
    def test_construction(self, same_on_batch, keepdim, random_apply):
        aug = K.ImageSequential(
            K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
            K.RandomAffine(360, p=1.0),
            K.RandomMixUpV2(p=1.0),
            same_on_batch=same_on_batch,
            keepdim=keepdim,
            random_apply=random_apply,
        )
        aug.same_on_batch = True
        aug.keepdim = True
        for m in aug.children():
            assert m.same_on_batch is True, m.same_on_batch
            assert m.keepdim is True, m.keepdim

    @pytest.mark.parametrize("random_apply", [1, (2, 2), (1, 2), (2,), 10, True, False])
    def test_forward(self, random_apply, device, dtype):
        with torch.random.fork_rng():
            torch.manual_seed(0)
            inp = torch.randn(1, 3, 30, 30, device=device, dtype=dtype)
            aug = K.ImageSequential(
                K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                kornia.filters.MedianBlur((3, 3)),
                K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0),
                K.ImageSequential(K.ColorJiggle(0.1, 0.1, 0.1, 0.1, p=1.0)),
                K.ImageSequential(K.RandomAffine(360, p=1.0)),
                K.RandomAffine(360, p=1.0),
                K.RandomMixUpV2(p=1.0),
                random_apply=random_apply,
            )
            out = aug(inp)
            assert out.shape == inp.shape
            reproducibility_test(inp, aug)


@pytest.mark.usefixtures("restore_torch_rng")
class TestConventionImageSequential(BaseTester):
    """Batch-6 convention pins for `ImageSequential`.

    Literals generated by the body of each pin, executed on this worktree on 2026-09-11 with
    `.venv/bin/python` (torch 2.14.0, python 3.11, cpu, float32).
    """

    def test_convention_if_unsupported_ops_skip_leaves_plain_modules_applied_4423(self, device, dtype):
        # #4423: the inverse used to skip a plain `nn.Module` under every value of the flag. That behavior is now
        # what "skip" selects: `inverse` undoes only the invertible members and returns something that is not the
        # input. The deterministic checkerboard ensures the omitted blur visibly changes the output.
        if device.type == "mps" and torch_version_lt(2, 6, 0):
            pytest.skip("torch 2.5.1 MPS inverse of expanded matrices can abort the process")
        yy, xx = torch.meshgrid(torch.arange(6, device=device), torch.arange(8, device=device), indexing="ij")
        x = ((yy + xx) % 2).to(dtype).expand(2, 3, 6, 8)
        assert K.ImageSequential(K.RandomHorizontalFlip(p=1.0)).if_unsupported_ops == "raise"
        seq = K.ImageSequential(
            K.RandomHorizontalFlip(p=1.0),
            kornia.filters.GaussianBlur2d((3, 3), (1.5, 1.5)),
            if_unsupported_ops="skip",
        )
        out = seq(x)
        inverted = seq.inverse(out)
        self.assert_close(inverted, out.flip(-1))  # only the flip was undone, the blur was skipped
        assert (inverted - x).abs().max().item() > 0.1  # and the round trip is not the input

    def test_convention_slice_crop_inverse_raises(self, device, dtype):
        seq = K.ImageSequential(K.CenterCrop((4, 6), p=1.0))
        out = seq(torch.rand(1, 3, 6, 8, device=device, dtype=dtype))
        with pytest.raises(NotImplementedError, match="resample cropping mode"):
            seq.inverse(out)

    def test_convention_get_transformation_matrix_recomputes_older_params(self, device, dtype):
        # Module matrices hold only the most recent call. Supplying recorded parameters from an earlier call
        # therefore requires recompute=True.
        image = torch.rand(1, 3, 6, 8, device=device, dtype=dtype)
        seq = K.ImageSequential(K.RandomHorizontalFlip(p=0.5), K.RandomVerticalFlip(p=0.5))
        torch.manual_seed(1)
        seq(image)
        old_params = seq._params
        torch.manual_seed(101)
        seq(image)
        current = seq.get_transformation_matrix(image, old_params)
        recomputed = seq.get_transformation_matrix(image, old_params, recompute=True)
        assert current is not None and recomputed is not None
        assert not torch.equal(current, recomputed)

    def test_convention_if_unsupported_ops_raise_raises_not_implemented(self, device, dtype):
        # #4423: `if_unsupported_ops` defaults to "raise", so inverting a chain that holds a non-invertible
        # plain `nn.Module` raises `NotImplementedError` rather than silently skipping it.
        if device.type == "mps" and torch_version_lt(2, 6, 0):
            pytest.skip("torch 2.5.1 MPS inverse of expanded matrices can abort the process")
        x = torch.rand(2, 3, 6, 8, device=device, dtype=dtype)
        seq = K.ImageSequential(
            K.RandomHorizontalFlip(p=1.0),
            kornia.filters.GaussianBlur2d((3, 3), (1.5, 1.5)),
            if_unsupported_ops="raise",
        )
        out = seq(x)
        with pytest.raises(NotImplementedError):
            seq.inverse(out)

    def test_convention_if_unsupported_ops_raise_leaves_intensity_augmentations_applied_4423(self, device, dtype):
        # #4423: "raise" is about plain `nn.Module` members only. An intensity augmentation has no geometry to
        # undo and is left applied on the inverse path, as before, under both settings.
        if device.type == "mps" and torch_version_lt(2, 6, 0):
            pytest.skip("torch 2.5.1 MPS inverse of expanded matrices can abort the process")
        x = torch.rand(2, 3, 6, 8, device=device, dtype=dtype)
        seq = K.ImageSequential(K.RandomHorizontalFlip(p=1.0), K.ColorJiggle(0.3, 0.3, p=1.0))
        out = seq(x)
        self.assert_close(seq.inverse(out), out.flip(-1))

    def test_convention_if_unsupported_ops_applies_to_each_container_own_members_4423(self, device, dtype):
        # #4423: a nested container inverts its own members, so its own setting decides for the plain modules it
        # holds, and a nested container is never itself an unsupported member of the outer one.
        if device.type == "mps" and torch_version_lt(2, 6, 0):
            pytest.skip("torch 2.5.1 MPS inverse of expanded matrices can abort the process")
        x = torch.rand(2, 3, 6, 8, device=device, dtype=dtype)
        blur = kornia.filters.GaussianBlur2d((3, 3), (1.5, 1.5))

        inner_skips = K.ImageSequential(
            K.RandomHorizontalFlip(p=1.0),
            K.ImageSequential(blur, if_unsupported_ops="skip"),
            if_unsupported_ops="raise",
        )
        out = inner_skips(x)
        self.assert_close(inner_skips.inverse(out), out.flip(-1))

        inner_raises = K.ImageSequential(
            K.RandomHorizontalFlip(p=1.0),
            K.ImageSequential(blur, if_unsupported_ops="raise"),
            if_unsupported_ops="skip",
        )
        out = inner_raises(x)
        with pytest.raises(NotImplementedError, match="GaussianBlur2d"):
            inner_raises.inverse(out)

    def test_convention_video_sequential_passes_if_unsupported_ops_through_4423(self, device, dtype):
        # #4423: VideoSequential inverts through ImageSequential, so it takes the same setting.
        x = torch.rand(1, 3, 3, 6, 8, device=device, dtype=dtype)
        blur = kornia.filters.GaussianBlur2d((3, 3), (1.5, 1.5))
        raises = K.VideoSequential(K.RandomHorizontalFlip(p=1.0), blur)
        assert raises.if_unsupported_ops == "raise"
        out = raises(x)
        with pytest.raises(NotImplementedError, match="GaussianBlur2d"):
            raises.inverse(out)
        skips = K.VideoSequential(K.RandomHorizontalFlip(p=1.0), blur, if_unsupported_ops="skip")
        out = skips(x)
        self.assert_close(skips.inverse(out), out.flip(-1))
        with pytest.raises(ValueError):
            K.VideoSequential(K.RandomHorizontalFlip(p=1.0), if_unsupported_ops="bogus")

    def test_convention_if_unsupported_ops_rejects_invalid_value(self):
        # #4423: construction accepts only "raise" and "skip".
        with pytest.raises(ValueError):
            K.ImageSequential(K.RandomHorizontalFlip(p=1.0), if_unsupported_ops="bogus")
