name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "help wanted"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        **Before submitting:**
        - [ ] I have searched existing issues to ensure this bug hasn't been reported
        - [ ] I have checked the [help wanted issues](https://github.com/kornia/kornia/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22help%20wanted%22) list
        - [ ] I have read the [Contributing Guide](https://github.com/kornia/kornia/blob/main/CONTRIBUTING.md)

  - type: textarea
    id: describe-bug
    attributes:
      label: 🐛 Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Example: When I call function X with parameters Y, I get error Z instead of the expected result.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior. Include minimal code example if possible.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: 💻 Minimal Code Example
      description: If applicable, provide a minimal code example that reproduces the bug
      placeholder: |
        ```python
        import kornia
        # Your minimal code here
        ```
      render: python
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual behavior
      description: What actually happened? Include error messages if any.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🔧 Environment
      description: Please provide your environment details
      value: |
        - Kornia version:
        - PyTorch version:
        - Python version:
        - OS (e.g., Linux, macOS, Windows):
        - Installation method (pip, conda, from source):
        - CUDA/cuDNN version (if applicable):
        - GPU model (if applicable):

        You can also run:
        ```bash
        wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
        # For security purposes, please check the contents of collect_env.py before running it.
        python collect_env.py
        ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional context
      description: Add any other context, screenshots, or relevant information about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: contribution-intent
    attributes:
      label: 🤝 Contribution Intent
      description: Are you planning to contribute a fix for this bug?
      options:
        - label: I plan to submit a PR to fix this bug
          required: false
        - label: I'm reporting this bug but not planning to fix it
          required: false
