FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
         curl \
         bzip2 \
         ca-certificates &&\
rm -rf /var/lib/apt/lists/*

COPY . /torchgeometry
WORKDIR /torchgeometry

RUN ./setup_travis_env.sh
