name: tests-lts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [open, reopened, synchronize, review_requested, ready_for_review]
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-cpu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install curl -c conda-forge
        conda install pytorch cpuonly -c pytorch-lts
        pip install .[all]
    - name: Run Tests
      shell: bash -l {0}
      run: pytest -v --device cpu --dtype float32,float64 --cov=kornia --cov-report xml ./test --mypy
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: cpu,pytest,torch-lts-1.8.2
        name: cpu-coverage
