<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
=======
<<<<<<< master
>>>>>>> [Feat] Add Github Actions as main CI (#744)
name: tests-cpu-versions

on:
  push:
   branches:
     - master
  # pull_request:
=======
name: test-cpu-versions

on:
  #push:
  #  branches:
  #    - master
  #pull_request:
>>>>>>> [Feat] Add Github Actions as main CI (#744)
<<<<<<< refs/remotes/kornia/master
=======
name: tests-cpu-versions

on:
  push:
   branches:
     - master
  # pull_request:
>>>>>>> [Feat] Enabled Torch1.5.1 cpu support (#796)
=======
>>>>>>> [Feat] Add Github Actions as main CI (#744)
  schedule:
    - cron: "0 4 * * *"

jobs:
  test-cpu-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
        pytorch-version: [1.5.1, 1.6.0, 1.7.0]
<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
=======
<<<<<<< master
>>>>>>> [Feat] Add Github Actions as main CI (#744)
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
=======
        pytorch-channel: [pytorch]
        include:
        - os: ubuntu-latest
          pytorch-channel: pytorch-nightly
<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
        - os: macos-latest
          pytorch-channel: pytorch-nightly
        - os: windows-latest
          pytorch-channel: pytorch-nightly
=======
>>>>>>> [Feat] update to pytorch 1.7 (#768)
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
<<<<<<< refs/remotes/kornia/master
      uses: conda-incubator/setup-miniconda@v1
>>>>>>> [Feat] Add Github Actions as main CI (#744)
=======
      uses: conda-incubator/setup-miniconda@v2
>>>>>>> update setup-miniconda to v2 (#789)
=======
        include:
=======
>>>>>>> fix gh action versions issue with os matrix (#754)
        - os: macos-latest
          pytorch-channel: pytorch-nightly
        - os: windows-latest
          pytorch-channel: pytorch-nightly
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v1
>>>>>>> [Feat] Add Github Actions as main CI (#744)
>>>>>>> [Feat] Add Github Actions as main CI (#744)
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install curl make -c conda-forge
<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
<<<<<<< refs/remotes/kornia/master
        conda install pytorch=${{ matrix.pytorch-version }} cpuonly -c pytorch
=======
        conda install pytorch=${{ matrix.pytorch-version }} cpuonly -c ${{ matrix.pytorch-channel }}
>>>>>>> [Feat] Add Github Actions as main CI (#744)
=======
        conda install pytorch=${{ matrix.pytorch-version }} cpuonly -c pytorch
>>>>>>> [Feat] update to pytorch 1.7 (#768)
=======
<<<<<<< master
        conda install pytorch=${{ matrix.pytorch-version }} cpuonly -c pytorch
=======
        conda install pytorch=${{ matrix.pytorch-version }} cpuonly -c ${{ matrix.pytorch-channel }}
>>>>>>> [Feat] Add Github Actions as main CI (#744)
>>>>>>> [Feat] Add Github Actions as main CI (#744)
        pip install -r requirements-dev.txt
        make install
    - name: Run Tests
      shell: bash -l {0}
      run: pytest -v --device cpu --dtype float32,float64 --cov=kornia --cov-report xml ./test --flake8 --mypy
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
