name: test-nightly

on:
  #push:
  #  branches:
  #    - master
  #pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  test-cpu-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install curl make -c conda-forge
        conda install pytorch cpuonly -c pytorch-nightly
        pip install -r requirements-dev.txt
        make install
    - name: Run Tests
      shell: bash -l {0}
      run: pytest -v --device cpu --dtype float32,float64 ./test --flake8 --mypy
