name: Tests on CPU (nightly)

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
  push:
    branches: [master]
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-cpu:
    name: ${{ matrix.os }} - python-${{ matrix.python-version }}, torch-${{ matrix.pytorch-version }}, ${{ matrix.pytorch-dtype }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['Ubuntu', 'Windows', 'MacOS']
        python-version: ['3.7', '3.8']
        pytorch-version: ['nightly']
        pytorch-dtype: ['float32', 'float64']

    steps:
      - name: Checkout kornia
        uses: actions/checkout@v3

      - name: Setting environment on ${{ matrix.os }} with python ${{ matrix.python-version }} and pytorch  ${{ matrix.pytorch-version }}
        uses: ./.github/actions/env
        with:
          python-version: ${{ matrix.python-version }}
          pytorch-version: ${{ matrix.pytorch-version }}

      - name: Run CPU tests ${{ matrix.pytorch-dtype }}
        shell: bash -l {0}
        run: pytest -v --device cpu --dtype ${{ matrix.pytorch-dtype }} --cov=kornia --cov-report xml ./test


      - if: always()
        name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # to not depend on build via GH API
          flags: cpu,${{ matrix.os }}_py-${{ matrix.python-version }}_pt-${{ matrix.pytorch-version }}_${{ matrix.pytorch-dtype }}
          name: cpu-coverage
